# netlify.toml
[build]
command = "npm run build"
publish = "dist" # Adjust if your publish directory is different

[images]
# Allow remote images from specific domains, using regex
remote_images = ["https://admindashboard.comcitybd.com/*"]