# netlify.toml
[build]
command = "npm run generate"
publish = "dist" # Adjust if your publish directory is different

[images]
# Allow remote images from specific domains, using regex
remote_images = ["https://admindash.comcitybd.com/*"]